# Generated by Django 2.2.4 on 2019-09-20 01:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='receive_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 20, 1, 2, 8, 810810, tzinfo=utc), verbose_name='Receive Date'),
            preserve_default=False,
        ),
    ]
