# Generated by Django 2.2.4 on 2019-09-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190924_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receive',
            options={'ordering': ['receive_date', 'updated_time']},
        ),
    ]
