# Generated by Django 2.2.4 on 2019-09-24 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_clientorder_job_id'),
        ('accounts', '0011_auto_20190924_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('RMB', 'RMB'), ('EUR', 'EUR')], default='USD', max_length=5, verbose_name='Currency')),
                ('need_jiehui', models.BooleanField(default=False, verbose_name='Jiehui')),
                ('trueAmount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account', verbose_name='Account')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Client')),
                ('clientorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientOrder', verbose_name='Order')),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Payee', verbose_name='Payee')),
                ('transfer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Transfer', verbose_name='Transfer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderTotalAmount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Order Amount')),
                ('productTotalAmount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Total Amount')),
                ('co', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientOrder', verbose_name='Order')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(max_length=100, verbose_name='Payer Name')),
                ('transfer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Transfer', verbose_name='Transfer')),
            ],
        ),
    ]
