# Generated by Django 2.2.4 on 2019-09-25 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_income_orderpl_outcome_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='note',
            field=models.TextField(default='', verbose_name='Note'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='clientorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.ClientOrder', verbose_name='Order'),
        ),
    ]
