# Generated by Django 2.2.4 on 2019-09-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190925_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='type',
            field=models.CharField(default='IO', max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='trueAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount'),
        ),
    ]
