# Generated by Django 2.2.4 on 2019-09-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190925_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='trueAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='True Amount'),
        ),
    ]
