# Generated by Django 2.2.4 on 2019-09-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190925_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receive',
            name='account',
        ),
        migrations.RemoveField(
            model_name='receive',
            name='client',
        ),
        migrations.RemoveField(
            model_name='receive',
            name='clientorder',
        ),
        migrations.RemoveField(
            model_name='receive',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Receive',
        ),
    ]
