# Generated by Django 2.2.4 on 2019-09-25 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_auto_20190925_1612'),
        ('accounts', '0016_auto_20190925_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoFinanceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('orderAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Order Amount ')),
                ('orderCurrency', models.CharField(choices=[('USD', 'USD'), ('RMB', 'RMB'), ('EUR', 'EUR')], max_length=10, verbose_name='Order Currency')),
                ('cpAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='OrderItem Total')),
                ('incomeTotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Income Total')),
                ('trueIncomeTotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Income Total')),
                ('outcomeTotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Outcome Total')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='P&L')),
                ('co', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientOrder', verbose_name='Client Order')),
            ],
        ),
    ]
