# Generated by Django 2.2.4 on 2019-09-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_cofinanceinfo_needjiehuiqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofinanceinfo',
            name='unpaidTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unpaid Total'),
        ),
    ]
