# Generated by Django 2.2.4 on 2019-09-27 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_auto_20190925_1612'),
        ('accounts', '0019_cofinanceinfo_unpaidtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('orderAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Order Amount ')),
                ('orderCurrency', models.CharField(choices=[('USD', 'USD'), ('RMB', 'RMB'), ('EUR', 'EUR')], max_length=10, verbose_name='Order Currency')),
                ('cpAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='OrderItem Total')),
                ('incomeTotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Income Total')),
                ('unpaidTotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unpaid Total')),
                ('rmbIncomeTotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='人民币总收款')),
                ('rmbOutcomeTotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='人民币总付款')),
                ('rmbProfit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='人民币净利润')),
                ('needJiehuiQty', models.PositiveIntegerField(default=0, verbose_name='TBD Jiehui')),
                ('co', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientOrder', verbose_name='Client Order')),
            ],
        ),
    ]
