# Generated by Django 2.2.4 on 2019-09-29 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20190929_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('balance_date', models.DateField(default=datetime.date(2019, 9, 29), verbose_name='Balance Date')),
                ('previousBalance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Previous Balance')),
                ('activitySum', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Activity Sum')),
                ('adjustBalance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Adjust Balance')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account', verbose_name='Account')),
                ('parentABNode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nextBalance', to='accounts.AccountBalance', verbose_name='Parent Account Balance')),
            ],
        ),
    ]
