# Generated by Django 2.2.4 on 2019-10-11 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20191010_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='balance_date',
            field=models.DateField(default=datetime.date(2019, 10, 11), verbose_name='Balance Date'),
        ),
    ]
