# Generated by Django 2.2.4 on 2019-10-14 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20191011_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='activitySum',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Activity Sum'),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='adjustBalance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Adjust Balance'),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='balance_date',
            field=models.DateField(default=datetime.date(2019, 10, 14), verbose_name='Balance Date'),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='previousBalance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Previous Balance'),
        ),
        migrations.AlterField(
            model_name='cosummary',
            name='cpAmount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='OrderItem Total'),
        ),
        migrations.AlterField(
            model_name='cosummary',
            name='incomeTotal',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Income Total'),
        ),
        migrations.AlterField(
            model_name='cosummary',
            name='orderAmount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Order Amount '),
        ),
        migrations.AlterField(
            model_name='cosummary',
            name='rmbIncomeTotal',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='人民币总收款'),
        ),
        migrations.AlterField(
            model_name='cosummary',
            name='rmbOutcomeTotal',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='人民币总付款'),
        ),
        migrations.AlterField(
            model_name='cosummary',
            name='rmbProfit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='人民币净利润'),
        ),
        migrations.AlterField(
            model_name='cosummary',
            name='rmbProfitRatio',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='利润率'),
        ),
        migrations.AlterField(
            model_name='cosummary',
            name='unpaidTotal',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Unpaid Total'),
        ),
        migrations.AlterField(
            model_name='orderpl',
            name='orderTotalAmount',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Order Amount'),
        ),
        migrations.AlterField(
            model_name='orderpl',
            name='productTotalAmount',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Product Total Amount'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='trueAmount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='True Amount'),
        ),
    ]
