# Generated by Django 2.2.4 on 2019-09-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='level',
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Manager', 'Manager')], default='Sales', max_length=10, verbose_name='Role'),
        ),
    ]
