# Generated by Django 2.2.4 on 2019-10-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20190924_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('L1', 'Sales'), ('L2', 'Manager'), ('L3', 'Account')], default='Sales', max_length=10, verbose_name='Role'),
        ),
    ]
