# Generated by Django 2.2.4 on 2019-09-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='priceUSD',
        ),
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.CharField(default='OTHER', max_length=10, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('RMB', 'RMB'), ('EUR', 'EUR')], default='USD', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='priceRMB',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Price(RMB)'),
            preserve_default=False,
        ),
    ]
