# Generated by Django 2.2.4 on 2019-09-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20190911_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Create Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='source',
            field=models.CharField(choices=[('ALIBABA', 'Alibaba'), ('EMAIL', 'EMAIL'), ('OTHER', 'OTHER')], default='OTHER', max_length=10, verbose_name='Source'),
        ),
    ]
