# Generated by Django 2.2.4 on 2019-09-11 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20190911_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ClientProduct',
        ),
    ]
