# Generated by Django 2.2.4 on 2019-09-11 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0006_auto_20190911_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('RMB', 'RMB'), ('EUR', 'EUR')], default='USD', max_length=5)),
                ('priceTerm', models.CharField(choices=[('FOB', 'FOB'), ('EXW', 'EXW'), ('ST', 'Tax + Shipping'), ('S', 'Shipping Only(No Tax)'), ('T', 'Tax(No Shipping')], default='FOB', max_length=5, verbose_name='Price Term')),
                ('priceRMB', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price(RMB)')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('cp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientProduct', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='productprice',
        ),
    ]
