# Generated by Django 2.2.4 on 2019-09-11 15:09

import clients.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0007_auto_20190911_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cost(RMB)')),
                ('cbom', models.ImageField(upload_to=clients.models.cpcost_directory_path, verbose_name='CBOM IMAGE')),
                ('cp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientProduct', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
