# Generated by Django 2.2.4 on 2019-09-12 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0008_cpcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('RMB', 'RMB'), ('EUR', 'EUR')], default='USD', max_length=5)),
                ('priceTerm', models.CharField(choices=[('FOB', 'FOB'), ('EXW', 'EXW'), ('ST', 'Tax + Shipping'), ('S', 'Shipping Only(No Tax)'), ('T', 'Tax(No Shipping')], default='FOB', max_length=5, verbose_name='Price Term')),
                ('priceRMB', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price(RMB)')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cost(RMB)')),
                ('unit_size', models.CharField(blank=True, help_text='L*W*H(cm)', max_length=50, null=True, verbose_name='Unit Size')),
                ('material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Material')),
                ('cp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientProduct', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
