# Generated by Django 2.2.4 on 2019-09-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_cpinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpinfo',
            name='carton_gw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Carton G.W.(KG)'),
        ),
        migrations.AddField(
            model_name='cpinfo',
            name='carton_nw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Carton N.W.(KG)'),
        ),
        migrations.AddField(
            model_name='cpinfo',
            name='carton_size',
            field=models.CharField(blank=True, help_text='L*W*H(cm)', max_length=50, null=True, verbose_name='Carton Size'),
        ),
        migrations.AddField(
            model_name='cpinfo',
            name='qty_carton',
            field=models.PositiveIntegerField(default=0, verbose_name='Units Per Carton'),
        ),
        migrations.AddField(
            model_name='cpinfo',
            name='unit_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Unit Weight(g)'),
        ),
    ]
