# Generated by Django 2.2.4 on 2019-09-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_clientorder_costatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costatus',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('PENDING', 'PENDING'), ('COMPLETE', 'COMPLETE'), ('CANCEL', 'CANCEL'), ('SOS', 'SOS')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
    ]
