# Generated by Django 2.2.4 on 2019-09-17 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_auto_20190917_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='contactor',
            field=models.CharField(default='', max_length=100, verbose_name='Client Contactor'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('RMB', 'RMB'), ('EUR', 'EUR')], default='USD', max_length=5, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='deliveryDate',
            field=models.DateField(default='2099-01-01', verbose_name='Delivery Date'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='po_number',
            field=models.CharField(default='N/A', max_length=50, verbose_name='PO'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Amount'),
        ),
        migrations.CreateModel(
            name='CoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('PO_NUM', models.CharField(default='N/A', max_length=50, verbose_name='')),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientOrder')),
            ],
        ),
    ]
