# Generated by Django 2.2.4 on 2019-09-17 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_auto_20190917_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoInfo',
        ),
    ]
