# Generated by Django 2.2.4 on 2019-09-17 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0015_delete_coinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='Qty')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('RMB', 'RMB'), ('EUR', 'EUR')], default='USD', max_length=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sub-Total')),
                ('note', models.CharField(max_length=100, verbose_name='Note')),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientOrder', verbose_name='ClientOrder')),
                ('cp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientProduct', verbose_name='Client Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created User')),
            ],
        ),
    ]
