# Generated by Django 2.2.4 on 2019-09-24 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_auto_20190918_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpinfo',
            name='cp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientProduct', verbose_name='Product'),
        ),
    ]
