# Generated by Django 2.2.4 on 2019-09-24 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_auto_20190924_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Contactor Name')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('wechat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wechat')),
                ('skype', models.CharField(blank=True, max_length=100, null=True, verbose_name='skype')),
                ('tel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tel')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
