# Generated by Django 2.2.4 on 2019-09-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_clientorder_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('PENDING', 'PENDING'), ('COMPLETE', 'COMPLETE'), ('CANCEL', 'CANCEL'), ('SOS', 'SOS')], default='PENDING', max_length=10),
        ),
    ]
