# Generated by Django 2.2.4 on 2019-10-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_auto_20190925_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproduct',
            name='expired',
            field=models.BooleanField(default=False, verbose_name='Expired Product'),
        ),
        migrations.AlterField(
            model_name='clientcontactor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Contactor Name(*)'),
        ),
        migrations.AlterField(
            model_name='clientcontactor',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Position(*)'),
        ),
    ]
