# Generated by Django 2.2.4 on 2019-10-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_auto_20191010_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproduct',
            name='type',
            field=models.CharField(choices=[('PRODUCT', '产品'), ('SHIPPING', '运费'), ('MOLD', '磨具')], default='PRODUCT', max_length=20, verbose_name='类目'),
        ),
    ]
