# Generated by Django 2.2.4 on 2019-10-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_clientproduct_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpinfo',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
