# Generated by Django 2.2.4 on 2019-10-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_cpinfo_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='totalAmount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='cpinfo',
            name='carton_gw',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Carton G.W.(KG)'),
        ),
        migrations.AlterField(
            model_name='cpinfo',
            name='carton_nw',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Carton N.W.(KG)'),
        ),
        migrations.AlterField(
            model_name='cpinfo',
            name='cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Cost(RMB)'),
        ),
        migrations.AlterField(
            model_name='cpinfo',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='cpinfo',
            name='priceRMB',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Price(RMB)'),
        ),
        migrations.AlterField(
            model_name='cpinfo',
            name='unit_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Unit Weight(g)'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Sub-Total'),
        ),
    ]
