# Generated by Django 2.2.4 on 2019-10-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_auto_20191014_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpinfo',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Price'),
        ),
    ]
