# Generated by Django 2.2.4 on 2019-10-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_auto_20191017_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpinfo',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, verbose_name='Price'),
        ),
    ]
