# Generated by Django 2.2.4 on 2019-10-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0030_auto_20191017_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpinfo',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Price'),
        ),
    ]
