# Generated by Django 2.2.4 on 2019-10-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0031_auto_20191017_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpinfo',
            name='priceRMB',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Price(RMB)'),
        ),
    ]
